matrix:
  include:
    - language: cpp
      compiler: clang
      script:
        - make && ./dataset_gen 1000 && ./blotto_ml dataset.txt output.txt && python3 ml_test.py && make clean

#    - language: python
#      python: 
#        - "3.6"
#      install:
#        - pip3 install -r requirements.txt
#      script:
#        - python3 ml_test.py
#      after_script:
#        - make clean
